// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIVILZeBlKPZjOnx3tjO4UmIKrTeSxI3s',
    appId: '1:669022475911:web:5706fe808e554599780a22',
    messagingSenderId: '669022475911',
    projectId: 'chat-app-9b132',
    authDomain: 'chat-app-9b132.firebaseapp.com',
    storageBucket: 'chat-app-9b132.appspot.com',
    measurementId: 'G-W7Z3Q1J2XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDDPDOJMhA-OizHkuncgQv7bw0Ox-WFmU',
    appId: '1:669022475911:android:82c20d51cd5f6536780a22',
    messagingSenderId: '669022475911',
    projectId: 'chat-app-9b132',
    storageBucket: 'chat-app-9b132.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCczm41mQdlQmJx-5gdOp_SV5q4-W_A5jw',
    appId: '1:669022475911:ios:fe42122feefe904f780a22',
    messagingSenderId: '669022475911',
    projectId: 'chat-app-9b132',
    storageBucket: 'chat-app-9b132.appspot.com',
    iosClientId:
        '669022475911-euh38svjl8uhpos2vqjh58fmct5p4bt5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatGroupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCczm41mQdlQmJx-5gdOp_SV5q4-W_A5jw',
    appId: '1:669022475911:ios:fe42122feefe904f780a22',
    messagingSenderId: '669022475911',
    projectId: 'chat-app-9b132',
    storageBucket: 'chat-app-9b132.appspot.com',
    iosClientId:
        '669022475911-euh38svjl8uhpos2vqjh58fmct5p4bt5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatGroupApp',
  );
}
